export const CITATION_TEMPLATE_FORMATS = [
  {
    is_default: "true",
    name: "APA - American Psychological Association 7th Edition",
    short_name: "APA",
    value: "apa",
    id: "1",
  },
  {
    is_default: "true",
    name: "Vancouver",
    short_name: "Vancouver",
    value: "vancouver",
    id: "2",
  },
  {
    is_default: "true",
    name: "Harvard",
    short_name: "Harvard",
    value: "harvard1",
    id: "3",
  },

  {
    is_default: "false",
    name: "MLA - Modern Language Association 9th Edition",
    short_name: "MLA",
    value: "modern-language-association",
    id: "4",
    file_path: "modern-language-association",
  },
  {
    is_default: "false",
    name: "Chicago Manual of Style 17th Edition (Full Note)",
    short_name: "Chicago (Full Note)",
    value: "chicago-fullnote-bibliography",
    id: "5",
    file_path: "chicago-fullnote-bibliography",
  },
  {
    is_default: "false",
    name: "Chicago Manual of Style 17th Edition (Author-Date)",
    short_name: "Chicago (Author-Date)",
    value: "chicago-author-date",
    id: "6",
    file_path: "chicago-author-date",
  },
  {
    is_default: "false",
    name: "AMA - American Medical Association 11th Edition",
    short_name: "AMA",
    value: "american-medical-association-alphabetical",
    id: "7",
    file_path: "american-medical-association-alphabetical",
  },
  {
    is_default: "false",
    name: "IEEE - Institute of Electrical and Electronics Engineers",
    short_name: "IEEE",
    value: "ieee",
    id: "8",
    file_path: "ieee",
  },
  {
    is_default: "false",
    name: "ACS - American Chemical Society",
    short_name: "ACS",
    value: "american-chemical-society",
    id: "9",
    file_path: "american-chemical-society",
  },
  {
    is_default: "false",
    name: "CSE - Council of Science Editors",
    short_name: "CSE",
    value: "council-of-science-editors-author-date",
    id: "10",
    file_path: "council-of-science-editors-author-date",
  },
  {
    is_default: "false",
    name: "ASA - American Sociological Association 6th Edition",
    short_name: "ASA",
    value: "american-sociological-association",
    id: "11",
    file_path: "american-sociological-association",
  },
  {
    is_default: "false",
    name: "APSA - American Political Science Association",
    short_name: "APSA",
    value: "american-political-science-association",
    id: "12",
    file_path: "american-political-science-association",
  },
  {
    is_default: "false",
    name: "AAA - American Anthropological Association",
    short_name: "AAA",
    value: "american-anthropological-association",
    id: "13",
    file_path: "american-anthropological-association",
  },
  {
    is_default: "false",
    name: "AIP - American Institute of Physics 4th Edition",
    short_name: "AIP",
    value: "american-institute-of-physics",
    id: "14",
    file_path: "american-institute-of-physics",
  },
  {
    is_default: "false",
    name: "OSCOLA - Oxford Standard for the Citation of Legal Authorities",
    short_name: "OSCOLA",
    value: "oscola",
    id: "15",
    file_path: "oscola",
  },
  {
    is_default: "false",
    name: "NLM - National Library of Medicine",
    short_name: "NLM",
    value: "national-library-of-medicine-grant-proposals",
    id: "16",
    file_path: "national-library-of-medicine-grant-proposals",
  },
];
